global using System.Collections;
global using System.IO.Abstractions;
global using System.Text.RegularExpressions;
global using Moq;
global using RepoAnalyzer.Core;
global using RepoAnalyzer.Core.Rules;
global using RepoAnalyzer.Core.Rules.FileLocation;
global using TruePath;
global using Xunit.Abstractions;
